# require_relative '../node_modules/react-native/scripts/react_native_pods'
# require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'


# # Add the Firebase pod for Google Analytics
# pod 'Firebase/Analytics'

# # Add the pods for any other Firebase products you want to use in your app
# # For example, to use Firebase Authentication and Cloud Firestore
# pod 'Firebase/Auth'
# pod 'Firebase/Firestore'
# platform :ios, '9.0'
# # pod 'RNCAsyncStorage', :path => '../node_modules/@react-native-async-storage/async-storage'
# pod 'BVLinearGradient', :path => '../node_modules/react-native-linear-gradient'
# target 'chatBot' do
#   config = use_native_modules!

#   use_react_native!(:path => config["reactNativePath"])


#   pod 'RNCAsyncStorage', :path => '../node_modules/@react-native-community/async-storage'

#   target 'chatBotTests' do
#     inherit! :complete
#     # Pods for testing
#   end
#   pod 'RNFBMessaging', :path => '../node_modules/@react-native-firebase/messaging'
#   pod 'Firebase/Messaging'
#   # Enables Flipper.
#   #
#   # Note that if you have use_frameworks! enabled, Flipper will not work and
#   # you should disable these next few lines.
# #  use_flipper!
# #  post_install do |installer|
# #    flipper_post_install(installer)
# #  end
# end

# target 'chatBot-tvOS' do
#   # Pods for chatBot-tvOS
#   # pod 'RNFBDatabase'
# end
#   target 'chatBot-tvOSTests' do
#     inherit! :search_paths
#     # Pods for testing
#     pod 'Firebase/Messaging'
#     # # pod for realtime firebase
#     # pod 'Firebase/Database'
#   end
#   # target 'chatBot' do
#     #  ...
#     pod 'RNFBDatabase', :path => '../node_modules/@react-native-firebase/database'
#   # end
# # end
require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

platform :ios, '10.0'

target 'chatBot' do
  config = use_native_modules!

  use_react_native!(:path => config["reactNativePath"])

  target 'chatBotTests' do
    inherit! :complete
    # Pods for testing
  end

  # Enables Flipper.
  #
  # Note that if you have use_frameworks! enabled, Flipper will not work and
  # you should disable these next few lines.
  # use_flipper!
  use_flipper!({ 'Flipper' => '0.87.0', 'Flipper-Folly' => '2.5.3', 'Flipper-RSocket' => '1.3.1' })
  post_install do |installer|
    flipper_post_install(installer)
  end
end

target 'chatBot-tvOS' do
  # Pods for chatBot-tvOS

  target 'chatBot-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end
end